### PR TITLE
update syn, quote and proc-macro2 to 1.0

### PR DESCRIPTION
**Pull request by Veykril**
Updates the respective dependencies to their 1.0 versions.

### CODE REVIEW

**Comment by azriel91** [comment]
ninja! (https://github.com/rustsim/alga/pull/88)

**Comment by Veykril** [comment]
Hahaha that's amazing. Unfortunately for me, I think your PR looks cleaner than mine + mine doesn't even build on stable 😅

**Comment by azriel91** [comment]
Haha, I got lucky on `stable` -- I work on nightly locally as well :stuck_out_tongue:

**Comment by sebcrozet** [comment]
Thanks @Veykril and @azriel91. I'll merge #88 instead of this one then.

**Pull request closed without merging**
